apiVersion: apps/v1beta2
kind: Deployment
metadata:
  name: golang-chatbot-deployment
  labels:
    app: golang-chatbot
spec:
  replicas: 2
  selector:
    matchLabels:
      app: golang-chatbot
  template:
    metadata:
      labels:
        app: golang-chatbot
    spec:
      containers:
      - name: golang-chatbot
        image: gcr.io/optimal-tide-243614/golang-chatbot:1.0
        imagePullPolicy: Always
        readinessProbe:
          httpGet:
            path: /
            port: 80
          periodSeconds: 1
          timeoutSeconds: 1
          successThreshold: 1
          failureThreshold: 10
