apiVersion: v1
kind: Service
metadata:
  name: golang-chatbot-service
  labels:
    app: golang-chatbot
spec:
  type: LoadBalancer
  ports:
    port: 8000
    targetPort: 80
  selector:
    app: golang-chatbot
    